{% macro events_columns_to_remove() %}

  {% set cols_to_remove = [
    'dvce_ismobile',
    'br_cookies',
    'br_features_silverlight',
    'br_features_gears',
    'br_features_windowsmedia',
    'br_features_realplayer',
    'br_features_quicktime',
    'br_features_director',
    'br_features_java',
    'br_features_flash',
    'br_features_pdf',
    'doc_height',
    'doc_width',
    'br_viewheight',
    'br_viewwidth',
    'pp_yoffset_max',
    'pp_yoffset_min',
    'pp_xoffset_max',
    'pp_xoffset_min',
    'refr_urlport',
    'page_urlport',
    'domain_sessionidx',
    'txn_id',
    'domain_sessionid',
    'refr_domain_userid',
    'mkt_network',
    'mkt_clickid',
    'doc_charset',
    'dvce_type',
    'os_timezone',
    'os_manufacturer',
    'os_family',
    'os_name',
    'br_colordepth',
    'br_lang',
    'br_renderengine',
    'br_type',
    'br_version',
    'br_family',
    'br_name',
    'mkt_campaign',
    'mkt_content',
    'mkt_term',
    'mkt_source',
    'mkt_medium',
    'refr_term',
    'refr_source',
    'refr_medium',
    'refr_urlfragment',
    'refr_urlquery',
    'refr_urlpath',
    'refr_urlhost',
    'refr_urlscheme',
    'page_urlfragment',
    'page_urlquery',
    'page_urlpath',
    'page_urlhost',
    'page_urlscheme',
    'page_referrer',
    'page_title',
    'page_url',
    'domain_userid',
    'user_fingerprint',
    'refr_dvce_tstamp'
  ] %}

  {{ return(cols_to_remove) }}
  
{% endmacro %}
